### ISSUE TITLE
Metadata.yaml has invalid content

### ISSUE THREAD

**Issue by philpott** [Zemanta/zem-conversion-pixel-gtm-template#5]
https://github.com/Zemanta/zem-conversion-pixel-gtm-template/blob/c7fa8e26a1cbeb7ad385f3bc783d28fa3bf96c3e/metadata.yaml#L1-L2

YAMLError: end of the stream or a document separator is expected at line 1, column 28:
  homepage: "www.zemanta.com",
                             ^ at line 1, column 28:
  homepage: "www.zemanta.com",

Once the first to lines are corrected (removing trailing commas) close this and we'll re-review your template.

**Comment by Katrca** [comment]
Fixed https://github.com/Zemanta/zem-conversion-pixel-gtm-template/pull/6

**Comment by jakasibicekaka** [comment]
Hi,

@philpott do you have any ETA for re-review of Zemanta's template?

Thanks for info.

BR
Jaka
(Zemanta Product Manager)
